Assignment_1_ds : main.o cir_queue.o display.o pop.o queue.o stack.o push.o cir_sll.o dll.o sll.o
	gcc -o ./out/Assignment_1_ds -Wall ./out/*.o
	./out/Assignment_1_ds

cir_queue.o : 
	gcc ./source/cir_queue.c -Wall -c -o ./out/cir_queue.o

display.o : 
	gcc ./source/display.c -Wall -c -o ./out/display.o

pop.o : 
	gcc ./source/pop.c -Wall -c -o ./out/pop.o

queue.o :
	gcc ./source/queue.c -Wall -c -o ./out/queue.o

stack.o :
	gcc ./source/stack.c -Wall -c -o ./out/stack.o

push.o :
	gcc ./source/push.c -Wall -c -o ./out/push.o

cir_sll.o :
	gcc ./source/cir_single_linked_list.c -Wall -c -o ./out/cir_sll.o

dll.o : 
	gcc ./source/double_linked_list.c -Wall -c -o ./out/dll.o

sll.o : 
	gcc ./source/single_linked_list.c -Wall -c -o ./out/sll.o

main.o :
	gcc ./source/Assignment_1.c -Wall -c -o ./out/main.o
